### ISSUE TITLE
出现了listen tcp :80: bind: address already in use

### ISSUE THREAD

**Issue by chenraotg** [gislu/gochat#4]
您好，请问如何才能修改gochat的端口占用呢？我服务器的80端口已经被Nginx占用了，我想把gochat的端口修改一下，请问在哪改呀？

**Comment by chenraotg** [comment]
后来我自己在conf里面找到app.conf文件修改为443了（因为微信设置里有说支持443端口），然后gochat也跑起来了，不过提交服务器配置之后，还是提示token验证失败，还请告知下问题出在哪里了

在此之前的环境搭建过程都是按照您的博客里的步骤一步一步来的，应该没啥问题

**Comment by chenraotg** [comment]
443端口对应的是https://
所以微信服务器配置处的URL我也填的是https://XX.XX.XX.XX/pub
token也填写得与id_relative.yaml中一致
但是点击提交后还是会提示token验证失败，求解。。。

**Comment by gislu** [comment]
Give me some time to check if there are some changes in WeChat official...

**Comment by gislu** [comment]
您好，443端口是https协议的，https跟http协议是完全不同的两个协议，如果想要适配https协议，还需要额外开发很多配置，建议您让gochat监听任意端口，然后利用nginx做端口映射，将80端口的内容映射到gochat监听的端口
如果nginx已经有代理的内容，您可以映射指定域名的信息到gochat，
可以参考这篇文章～：
 http://www.ttlsa.com/nginx/use-nginx-proxy/
如果这样还是会出现token错误的话，欢迎继续提交issue给我～

**Comment by chenraotg** [comment]
好的，我先去试试，多谢您~

**Comment by chenraotg** [comment]
因为后来东西要赶进度，所以直接有买了个服务器，最后还是搭建起来了，非常感谢您的热心解答~

**Comment by gislu** [comment]
不客气 : )
做的轮子有人用还是很开心的
