### ISSUE TITLE
我如果添加模块的话好扩展嘛？

### ISSUE THREAD

**Issue by BryantJames** [gislu/gochat#6]
我现在的业务是这样的，我要去数据库中查询对应的字段然后返回数据给公众号，我需要定时去查询兄弟，我是java开发

**Comment by BryantJames** [comment]
我的是服务号公司服务号

**Comment by gislu** [comment]
额，应该很好扩展。。。。就是不知道你的具体需求是什么

**Comment by BryantJames** [comment]
谢谢你，我已经搭建成功了现在就是和我本地数据库去连接了，感谢开源。我是一个java开发，但是java写这个真的很多累赘，再次感谢老铁，对我帮助很大
，我的业务是要每天定时推送信息，我是服务号。用户可以根据输入进行查询记录等。业务不负责，就是我go语言还在学习中，您的框架真的不错谢谢！




在 2018-08-16 23:23:33，"gislu" <notifications@github.com> 写道：


额，应该很好扩展。。。。就是不知道你的具体需求是什么

**Comment by gislu** [comment]
有人使用我也很开心哈 ： ）
这个框架的底层封装已经完成的差不多了，也没啥好维护的了。。。剩下的主要还是根据个人的业务逻辑去开发啦
