### ISSUE TITLE
您好开发者，我把您的项目放到腾讯云上面，但是出现的情况是，一段时间不访问就需要重新开启，运维这方面我不是很了解，但是您能和我说说嘛？

### ISSUE THREAD

**Issue by BryantJames** [gislu/gochat#7]
您好开发者，我把您的项目放到腾讯云上面，但是出现的情况是，一段时间不访问就需要重新开启，运维这方面我不是很了解，但是您能和我说说嘛？

**Comment by gislu** [comment]
您好， 编译好的项目在执行的时候，需要在指令上加上一个后台执行。
否则你的ssh一旦断开就会自动终止程序运行的
